const description =
  "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis nesciunt eum optio aliquid iste facilis, soluta accusamus, error, expedita consectetur ipsum cupiditate id praesentium. Commodi expedita deleniti minus facilis debitis.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis nesciunt eum optio aliquid iste facilis, soluta accusamus, error, expedita consectetur ipsum cupiditate id praesentium. Commodi expedita deleniti minus facilis debitis.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis nesciunt eum optio aliquid iste facilis, soluta accusamus, error, expedita consectetur ipsum cupiditate id praesentium. Commodi expedita deleniti minus facilis debitis.";

const composition =
  "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis nesciunt eum optio aliquid iste facilis, soluta accusamus, error, expedita consectetur ipsum cupiditate id praesentium. Commodi expedita deleniti minus facilis debitis.";

const use =
  "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis nesciunt eum optio aliquid iste facilis, soluta accusamus, error, expedita consectetur ipsum cupiditate id praesentium. Commodi expedita deleniti minus facilis debitis.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis nesciunt eum optio aliquid iste facilis, soluta accusamus, error, expedita consectetur ipsum cupiditate id praesentium. Commodi expedita deleniti minus facilis debitis.";

const constArticle = [
  "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis nesciunt eum optio aliquid iste facilis, soluta accusamus, error, expedita consectetur ipsum cupiditate id praesentium. Commodi expedita deleniti minus facilis debitis.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis nesciunt eum optio aliquid iste facilis, soluta accusamus, error, expedita consectetur ipsum cupiditate id praesentium. Commodi expedita deleniti minus facilis debitis.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis nesciunt eum optio aliquid iste facilis, soluta accusamus, error, expedita consectetur ipsum cupiditate id praesentium. Commodi expedita deleniti minus facilis debitis.",
  "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis nesciunt eum optio aliquid iste facilis, soluta accusamus, error, expedita consectetur ipsum cupiditate id praesentium. Commodi expedita deleniti minus facilis debitis.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis nesciunt eum optio aliquid iste facilis, soluta accusamus, error, expedita consectetur ipsum cupiditate id praesentium. Commodi expedita deleniti minus facilis debitis.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis nesciunt eum optio aliquid iste facilis, soluta accusamus, error, expedita consectetur ipsum cupiditate id praesentium. Commodi expedita deleniti minus facilis debitis.",
  "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis nesciunt eum optio aliquid iste facilis, soluta accusamus, error, expedita consectetur ipsum cupiditate id praesentium. Commodi expedita deleniti minus facilis debitis.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis nesciunt eum optio aliquid iste facilis, soluta accusamus, error, expedita consectetur ipsum cupiditate id praesentium. Commodi expedita deleniti minus facilis debitis.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis nesciunt eum optio aliquid iste facilis, soluta accusamus, error, expedita consectetur ipsum cupiditate id praesentium.Lorem Commodi expedita deleniti minus facilis debitis.",
  "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis nesciunt eum optio aliquid iste facilis, soluta accusamus, error, expedita consectetur ipsum cupiditate id praesentium. Commodi expedita deleniti minus facilis debitis.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis nesciunt eum optio aliquid iste facilis, soluta accusamus, error, expedita consectetur ipsum cupiditate id praesentium. Commodi expedita deleniti minus facilis debitis.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis nesciunt eum optio aliquid iste facilis, soluta accusamus, error, expedita consectetur ipsum cupiditate id praesentium. Commodi expedita deleniti minus facilis debitis.",
  "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis nesciunt eum optio aliquid iste facilis, soluta accusamus, error, expedita consectetur ipsum cupiditate id praesentium. Commodi expedita deleniti minus facilis debitis.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis nesciunt eum optio aliquid iste facilis, soluta accusamus, error, expedita consectetur ipsum cupiditate id praesentium. Commodi expedita deleniti minus facilis debitis.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quis nesciunt eum optio aliquid iste facilis, soluta accusamus, error, expedita consectetur ipsum cupiditate id praesentium. Commodi expedita deleniti minus facilis debitis.",
];

export { description, composition, use, constArticle };
